//Addition
console.log("Addidion");
console.log(4+4);
console.log(5+3);
//subtraction
console.log("Subtraction");
console.log(12-4);
console.log(16-8);
//Multiplication
console.log("Multiplication");
console.log(2*4);
console.log(2*2*2);
//Division
console.log("Division");
console.log(16/2);
console.log(24/3);